export const data = {
    HP: {   
        WoodWall: 250,
        StoneWall: 500,
        MetalWall: 1000,
        MHQWall: 2000,
        WoodenDoor: 200,
        MetalDoor: 250,
        GarageDoor: 600,
        MHQDoor: 1000,
        LadderHatch: 250,
        HighExternalWoodenWall: 500,
        HighExternalStoneWall: 500
    },
    c4: {
        WoodWall: 495,
        StoneWall: 275,
        MetalWall: 275,
        MHQWall: 275,
        WoodenDoor: 1100,
        MetalDoor: 440,
        GarageDoor: 440,
        MHQDoor: 440,
        LadderHatch: 440,
        HighExternalWoodenWall: 495,
        HighExternalStoneWall: 275
    },
    Rocket: {
      WoodWall: 247.6,
      StoneWall: 137.6,
      MetalWall: 137.6,
      MHQWall: 137.6,
      WoodenDoor: 550.4,
      MetalDoor: 220.4,
      GarageDoor: 220.4,
      MHQDoor: 220.4,
      LadderHatch: 220.4,
      HighExternalWoodenWall: 247.6,
      HighExternalStoneWall: 137.6
    },
    SpeedRocket:{
        WoodWall: 91.5,
        StoneWall: 31,
        MetalWall: 31,
        MHQWall: 31,
        WoodenDoor: 43.5,
        MetalDoor: 51,
        GarageDoor: 52,
        MHQDoor: 52,
        LadderHatch: 51,
        HighExternalWoodenWall: 91.5,
        HighExternalStoneWall: 91.5
    },
    Satchel: {
        WoodWall: 91.5,
        StoneWall: 51.5,
        MetalWall: 43.5,
        MHQWall: 43.5,
        WoodenDoor: 170,
        MetalDoor: 70,
        GarageDoor: 70,
        MHQDoor: 70,
        LadderHatch: 70,
        HighExternalWoodenWall: 91.5,
        HighExternalStoneWall: 51.5
    },
    Granade: {
        WoodWall: 2,
        StoneWall: 2,
        MetalWall: 1,
        MHQWall: 1,
        WoodenDoor: 5,
        MetalDoor: 5,
        GarageDoor: 5,
        MHQDoor: 34.5,
        LadderHatch: 34.5,
        HighExternalWoodenWall: 42,
        HighExternalStoneWall: 23.5
    },
    Bobovka: { 
        WoodWall: 19.5,
        StoneWall: 11,
        MetalWall: 9,
        MHQWall: 9,
        WoodenDoor: 35,
        MetalDoor: 14.5,
        GarageDoor: 14.5,
        MHQDoor: 14.5,
        LadderHatch: 14.5,
        HighExternalWoodenWall: 19.5,
        HighExternalStoneWall: 11
    }
  };